### ISSUE TITLE
varbinary columns

### ISSUE THREAD

**Issue by miffe** [LukeMauldin/lodbc#4]
When I try to read a varbinary column I get this:

```
panic: ODBC type not supported: {-3}. Column name: Bin

goroutine 1 [running]:
github.com/LukeMauldin/lodbc.(*rows).getField(0x11789980, 0x1, 0x0, 0x0, 0x410000, ...)
        C:/Go/src/pkg/github.com/LukeMauldin/lodbc/rows.go:191 +0x702         github.com/LukeMauldin/lodbc.(*rows).getRow(0x11789980, 0x117604a0, 0x1, 0x1, 0x117604a0, ...)
        C:/Go/src/pkg/github.com/LukeMauldin/lodbc/rows.go:114 +0x81 github.com/LukeMauldin/lodbc.(*rows).Next(0x11789980, 0x117604a0, 0x1, 0x1, 0x0, ...)
        C:/Go/src/pkg/github.com/LukeMauldin/lodbc/rows.go:75 +0x1a8 database/sql.(*Rows).Next(0x117899c0, 0x4a2418, 0x11760498)
        C:/Users/ADMINI~1/AppData/Local/Temp/2/bindist721200707/go/src/pkg/database/sql/sql.go:920 +0xe1 database/sql.(*Row).Scan(0x1178e7b0, 0x331774, 0x1, 0x1, 0x0, ...)
        C:/Users/ADMINI~1/AppData/Local/Temp/2/bindist721200707/go/src/pkg/database/sql/sql.go:1052 +0x167
```

**Test program**

```
package main 

import (
    _ "github.com/LukeMauldin/lodbc"
    "log"
    "database/sql"
)

const DSN = "Driver={SQL Server Native Client 10.0};Server=localhost\\sqlserver2008;Database=tempdb;Trusted_Connection=yes;"

func main() {
    db, err := sql.Open("lodbc", DSN)
    if err != nil {
        log.Fatal(err)
    }
    defer db.Close()

    row := db.QueryRow("select * from lodbctest")

    bin := make([]byte, 1024)

    if err = row.Scan(&bin); err != nil {
        log.Fatal(err)
    }
}
```

**Test table**

```
use tempdb;
go
create table lodbctest (
    Bin varbinary(max) not null,
);
go 
insert into lodbctest values(0xdeadbabe);
go
```

**Comment by LukeMauldin** [comment]
Yes, you are correct that VARBINARY columns are currently not supported.  If you would like to make the change to support them, there is only one file that needs to be updated: https://github.com/LukeMauldin/lodbc/blob/master/rows.go
There is a switch in that file that switches on the possible column types, but at the moment I am just not sure of the ODBC calls needed to read a VARBINARY field.  You can try adding VARBINARY to line 158 because I suspect it will probably be like VARCHAR but I am not sure.
